+ Fixed bug in svn validate_version with undefined reference to self.version + Add get_tag_name method.  This allows users of Rez (in place of a more   advanced configuration system) to more easily support different tag naming   conventions without having to apply larger patches to the SCM plugins. + Made the tag name a property as this creates a slightly nicer api. + Add get_version_from_tag method to return a Version object from a tag string.   This supports tags which are not just a version number, and potential   support for changing the tag name strategy over time. + Update SCM plugins to use tag_name property instead of package version.