Fix  fileno() error in Maya2022
Maya 2022 console don't have sys.__stdin__ is a None object. 
Although the comment said this is taken into account, but the code didn't implement this idea.

Using `resolved_context.save_resolved_context_file(file_path=rez_ctx_file)` in Maya 2022 will cause the following error
```
# Error: AttributeError: file ~~~~\rez\~~~\platform-windows\python-3.7\lib\site-packages\rez\utils\execution.py line 59: 'NoneType' object has no attribute 'fileno' # 
```